### ISSUE TITLE
Write after end error for large files with slower downstream consumers

### ISSUE THREAD

**Issue by ryanwilliamquinn** [saary/unfixated#1]
I ran into this error parsing larger files, where there were multiple chunks written to the transform method, and an asynchronous downstream consumer.  The problem is that the `end` method of the linestream is called too early (on the `end` event of the unfixated stream).  The end event of the unfixated stream occurs when it is done getting any data from upstream.  But this can potentially occur before the last transform call.

**Comment by ryanwilliamquinn** [comment]
@saary Thanks for the quick response.  Could you please publish this to npm when you are able?  Thank you.

**Comment by saary** [comment]
No problem 👍
Thank you for the contribution.
